# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('idle', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
                ('used', models.BigIntegerField()),
                ('shared', models.BigIntegerField()),
                ('buff_cache', models.BigIntegerField()),
                ('available', models.BigIntegerField()),
                ('swap', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_list', models.CommaSeparatedIntegerField(max_length=200)),
                ('in_speed', models.BigIntegerField()),
                ('up_speed', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user_number', models.IntegerField()),
                ('login_user_name_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('server_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('server_type', models.CharField(max_length=100)),
            ],
        ),
    ]
