# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryinfo',
            old_name='buff_cache',
            new_name='cache',
        ),
        migrations.RenameField(
            model_name='memoryinfo',
            old_name='shared',
            new_name='free',
        ),
        migrations.RenameField(
            model_name='memoryinfo',
            old_name='swap',
            new_name='swap_free',
        ),
        migrations.RemoveField(
            model_name='memoryinfo',
            name='used',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_type',
        ),
        migrations.AddField(
            model_name='server',
            name='os_type',
            field=models.CharField(choices=[('L', 'Linux'), ('W', 'Windows')], default='L', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='server_use_type',
            field=models.CharField(choices=[('Web', 'Web Server'), ('Dev', 'Dev Server'), ('DB', 'DB Server')], default='Web', max_length=100),
        ),
        migrations.AlterField(
            model_name='netinfo',
            name='port_list',
            field=models.TextField(),
        ),
    ]
