# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0002_auto_20171013_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryinfo',
            old_name='swap_free',
            new_name='shared',
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Monitor.Server'),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
