# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityRatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stat_time', models.DateTimeField(auto_now=True)),
                ('customer_buy', models.BigIntegerField()),
                ('system_total', models.BigIntegerField()),
            ],
        ),
    ]
